services:
  db:
    container_name: database
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopDB
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql 
volumes:
  mysql_data:
  mysql_config: